### ISSUE TITLE
release process should include all javascript libraries for UDFs

### ISSUE THREAD

**Issue by jaketf** [GoogleCloudPlatform/bigquery-utils#184]
Who owns this bucket? it isn't part of the release process.
We should have automation to use [webpack](https://medium.com/swlh/how-to-package-a-javascript-library-for-use-in-bigquery-2bf91061f66f) to stage js libs in a public GCS bucket owned by the release process.
 
https://github.com/GoogleCloudPlatform/bigquery-utils/blob/99f0864492d735157ba78fc97a6f435ed3f53237/udfs/community/nlp_compromise_number.sql#L23

**Comment by ryanmcdowell** [comment]
Assigning to @danieldeleo 

He was looking into a framework for managing javascript library dependencies for the repo
