### ISSUE TITLE
Make Dataset Location Configurable

### ISSUE THREAD

**Issue by ryanmcdowell** [GoogleCloudPlatform/bigquery-utils#2]
**Issue**
Currently the dataset location which functions are deployed is defaulted in the `build.sh` script to `US` with no option to override with an input parameter. Add a way to override this default.

**Workaround**
For those that have this issue, they can work around it by manually updating the location in the build script and executing it.

**Comment by afleisc** [comment]
UDFs are now deployed globally! Users can also specify location for local builds
