### ISSUE TITLE
Average slots calculation in job_execution.sql

### ISSUE THREAD

**Issue by shiwang-gcp** [GoogleCloudPlatform/bigquery-utils#223]
In the SQL, it calculates average slots as:

total_slot_ms / (TIMESTAMP_DIFF(end_time, start_time, MILLISECOND)) AS avg_slots

should we use sum(timeline.elapsed_ms), instead of "end_time - start_time", seems the elapsed_ms does not include waiting time? Thx

**Comment by ryanmcdowell** [comment]
The `timeline.elapsed` value is a periodically sampled value which will be close but may not exactly match the duration of the query.

The `end_time - start_time` calculation should not include time spend PENDING at the beginning of the query as once a query starts it is active. PENDING time would be defined as `start_time - create_time`.
