### ISSUE TITLE
Why is slot_count negative when action <> 'UPDATE'?

### ISSUE THREAD

**Issue by jamiet-msm** [GoogleCloudPlatform/bigquery-utils#304]
Thank you for providing this report, I've got it up and running against our data and I'm sure it will be very useful.

One problem though, our slot commitment is appearing as a negative number: 
![image](https://user-images.githubusercontent.com/79862277/191944830-cef66bc1-b2c1-4297-b1dd-73132d5f66a6.png)

its because the query for the "Commitments Timeline" data source includes this logic:

```
SUM(CASE WHEN cccp.action = 'UPDATE' THEN cccp.slot_count ELSE cccp.slot_count * -1 END)
```

This is causing our one commitment to be returned from the data source query:

```sql
SELECT
  change_timestamp,
  commitment_plan,
  action,
  EXTRACT(DATE FROM change_timestamp) AS start_date,
  IFNULL(
    LEAD(DATE_SUB(EXTRACT(DATE FROM change_timestamp), INTERVAL 1 DAY))
      OVER (PARTITION BY state ORDER BY change_timestamp),
    CURRENT_DATE()) AS stop_date,
  SUM(CASE WHEN cccp.action = 'UPDATE' THEN cccp.slot_count ELSE cccp.slot_count * -1 END)
    OVER (
      PARTITION BY state
      ORDER BY change_timestamp ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS slot_cummulative,
  ROW_NUMBER()
    OVER (
      PARTITION BY EXTRACT(DATE FROM change_timestamp)
      ORDER BY change_timestamp DESC
    ) AS rn
FROM
  region-eu.INFORMATION_SCHEMA.CAPACITY_COMMITMENT_CHANGES_BY_PROJECT AS cccp
WHERE
  state = 'ACTIVE'
  AND commitment_plan != 'FLEX'
ORDER BY change_timestamp
```
as

| change_timestamp | commitment_plan | action | start_date | stop_date | slot_cummulative | rn |
| -- | -- | -- | -- | -- | -- | -- |
| 2022-07-29 13:53:58.843000 UTC | MONTHLY | CREATE | 2022-07-29 | 2022-09-23 | -1500 | 1 |

Can you explain why this logic to `multiply by -1 if action <> 'UPDATE'` exists? TIA

**Comment by danieldeleo** [comment]
I'd have to investigate if this is expected behavior, but the logic is explained by the author's [comments in the source](https://github.com/GoogleCloudPlatform/bigquery-utils/blob/6e18831a8f738c58b6d5656ee29e3264899d8176/dashboards/system_tables/sql/daily_commitments.sql#L48) for that sql.

**Comment by jamiet-msm** [comment]
> so I think the logic should be:
> 
> ```
> SUM(CASE WHEN cccp.action = 'UPDATE' OR cccp.action = 'CREATE' THEN cccp.slot_count ELSE cccp.slot_count * -1 END)
> ```

I've made that change and our chart is looking more normal now 
![image](https://user-images.githubusercontent.com/79862277/191975314-3815725d-18f6-4b2c-b61b-5e9c02ae02c3.png)

**Comment by danieldeleo** [comment]
I agree with your proposal, I'll submit a PR to fix. Thanks for catching this!

**Comment by jamiet-msm** [comment]
you're welcome.Happy to help.
