### ISSUE TITLE
Unable to view the images in bigquery-utils folder. 

### ISSUE THREAD

**Issue by saivasanth528** [GoogleCloudPlatform/bigquery-utils#341]
I am exploring the bigquery-utils repo, but in the images folder, I cannot view any images. Please check this [link](https://github.com/GoogleCloudPlatform/bigquery-utils/tree/master/dashboards/system_tables/images/daily_utilization). Please update the links or images, such that end users can view it.

**Comment by afleisc** [comment]
Hi, the image links seem to be working now. Let us know if it is still a problem
