### ISSUE TITLE
Request: Handling for objects in json_extract_values function

### ISSUE THREAD

**Issue by sgoley** [GoogleCloudPlatform/bigquery-utils#350]
Issue: 
`bqutils.fn.json_extract_values` returns unusable values `[object Object]` when children are objects / sub collections.

Example:
![image](https://user-images.githubusercontent.com/10283176/221068485-861c9522-554f-427b-977c-9feac39be3b5.png)

Sample query: 

``` SQL
-- (select body from`bigquery-public-data.geo_whos_on_first.geojson` limit 100 )

with geojson as 
(select """{"id": 1259392143, "type": "Feature", "properties": {"edtf:cessation": "uuuu", "edtf:inception": "uuuu", "geom:area": 0.0, "geom:area_square_m": 0.0, "geom:bbox": "116.97547,32.41412,116.97547,32.41412", "geom:latitude": 32.41412, "geom:longitude": 116.97547, "gn:admin1_code": "1.0", "gn:asciiname": "Liuyingcun", "gn:country_code": "CN", "gn:dem": 25, "gn:feature_class": "P", "gn:feature_code": "PPL", "gn:geonameid": 10417093, "gn:latitude": 32.41412, "gn:longitude": 116.97547, "gn:modification_date": "2015-08-08", "gn:name": "Liuyingcun", "gn:population": 0, "gn:timezone": "Asia/Shanghai", "iso:country": "CN", "mz:hierarchy_label": 1, "mz:is_current": -1, "name:zho_x_preferred": ["\u5218\u90e2\u6751"], "src:geom": "geonames", "wof:belongsto": [85669739, 102191569, 85632695, 136253041, 890516233], "wof:breaches": [], "wof:concordances": {"gn:id": 10417093}, "wof:country": "CN", "wof:geomhash": "cabdc55714fc98313d2246b1c4f7fb0b", "wof:hierarchy": [{"continent_id": 102191569, "country_id": 85632695, "county_id": 890516233, "empire_id": 136253041, "locality_id": 1259392143, "region_id": 85669739}], "wof:id": 1259392143, "wof:lastmodified": 1537613321, "wof:name": "Liuyingcun", "wof:parent_id": 890516233, "wof:placetype": "locality", "wof:repo": "whosonfirst-data", "wof:superseded_by": [], "wof:supersedes": [], "wof:tags": []}, "bbox": [116.97547, 32.41412, 116.97547, 32.41412], "geometry": {"coordinates": [116.97547, 32.41412], "type": "Point"}}""" as body)

SELECT bqutil.fn.json_extract_keys(body) as jkeys, bqutil.fn.json_extract_values(body) as jvalues
FROM geojson

```
I used a single row here because the public dataset is 14GB and unpartitioned. 

Desired Output: 
`bqutils.fn.json_extract_values` returns a usable value (even just a json string) of the contents of those objects.

Thanks!

**Comment by sgoley** [comment]
Alternative might be to build something like this as a whole separate UDF:

CREATE temp  FUNCTION CUSTOM_JSON_EXTRACT(json STRING, json_path STRING) RETURNS STRING
LANGUAGE js AS """ 
  try {
     var obj = JSON.parse(json);
     var result;
     var arg;
     if (obj) {
        if (json_path && obj.hasOwnProperty(json_path)) {
          result = JSON.stringify(obj[json_path]);
        }
        return (result.length ? result : false);
     }
} catch (e) { return null }
""";

Source: https://medium.com/google-cloud/extracting-json-key-value-pairs-in-bigquery-1bb9d0ec0b6d

**Comment by afleisc** [comment]
@plaflamme Just contributed the json_extract_key_value_pairs function in #408 which should help with this use case, please let us know if there are any issues
