### ISSUE TITLE
BigQuery UDFs not available outside the US and documentation unclear?

### ISSUE THREAD

**Issue by brabster** [GoogleCloudPlatform/bigquery-utils#384]
Hi, #252 asked for the community UDFs to be made available in regions other than the US - I'm unable to find them.
I searched for bqutil in the BigQuery UI explorer component and got no results.

I searched for a specific function and found it in `bigquery-public-data.persistent_udfs` - which looks like the content of this repo's community UDFs, which I can't find mentioned anywhere in this repo's docs.

That dataset is in the US multi-region and I can't find an equivalent for the EU multi-region where I am.

- am I doing something dumb and not finding the right functions?
- are these functions available in the EU? #252 seemed to ask for them to be made available but maybe that got lost.
  - if not, can they be made available? It's a fairly big barrier for non-US SQL wranglers to have to deploy them somewhere

**Comment by afleisc** [comment]
Hello, UDFs are now available in all BQ supported regions! Please see #405 and [docs](https://github.com/GoogleCloudPlatform/bigquery-utils/tree/master/udfs#using-the-udfs) to use regional UDFs
