### ISSUE TITLE
Update typeof function for new RANGE datatype

### ISSUE THREAD

**Issue by vlulla** [GoogleCloudPlatform/bigquery-utils#416]
The `typeof` function will return`'UNKNOWN'` for the new `RANGE` data type. #415 adds statements to correctly return the `typeof` of this new data type.

The CI/CD bot generated lots of errors and i do not know how to address them.  I will be glad to fix them if i can get some guidance.

Thanks in advance!

**Comment by afleisc** [comment]
Hi @vlulla , thanks for your submission! I'll follow up with you in the PR comments
