### ISSUE TITLE
Exporting protobuf column with nested message definitions

### ISSUE THREAD

**Issue by kball-pa** [GoogleCloudPlatform/bigquery-utils#432]
I can successfully use the protobuf exporter tool for protobuf message types containing one or more primitive data types. 

However, when I compile a message type with nested definitions (i.e. one of the field types is another protobuf message), the serialization doesn't work.

Steps to reproduce:
1. Follow [these instructions](https://cloud.google.com/bigquery/docs/protobuf-export#python) to compile the below proto and upload the pbwrapper.js file to GCS:
```
// value.proto
syntax = "proto3";

package test.types;

message Value {
    oneof val {
        string str_val = 1;
        StringList str_list_val = 2;
    }
}

message StringList {
    repeated string values = 1;
}
```

The following query and UDF run without error; however the serialized values of the input structs are the same, despite the field values differing:
```
CREATE TEMP FUNCTION
  toProto(input STRUCT<strListVal ARRAY<STRING>>)
  RETURNS BYTES
    LANGUAGE js OPTIONS (library=["gs://test/pbwrapper.js"]
) AS r"""
let message = pbwrapper.setup("test.types.Value")
return pbwrapper.parse(message, input)
  """

SELECT
  toProto(STRUCT(["hello", "world"])) as test1,
  toProto(STRUCT(["foo", "bar"])) as test2
```
Output:
```
Row | test1 | test2
1   | YgA=  | YgA=
```

Tagging @ron-gal @afleisc since I saw some activity from y'all on the protobuf exporter tool in the repo's issues. Thanks in advance!

**Comment by ron-gal** [comment]
Hey @kball-pa !
Glad to see you're using the tool!
To get it to work, you need the following:
```
CREATE TEMP FUNCTION
  toProto(input STRUCT<strListVal STRUCT<values ARRAY<STRING>>>)
  RETURNS BYTES
    LANGUAGE js OPTIONS (library=["gs://test/pbwrapper.js"]
) AS r"""
let message = pbwrapper.setup("test.types.Value")
return pbwrapper.parse(message, input)
    """

SELECT
  toProto(STRUCT(STRUCT(["hello", "world"]))) as test1,
  toProto(STRUCT(STRUCT(["foo", "bar"]))) as test2
```

The reason for this is that `Value` has a nested type called `strListVal`, and `strListVal` has a nested array of strings called `values`, so you need a struct (=`Value`) that wraps a struct (=`strListVal`) that wraps an array of strings(=`values`).
Let me know if you have any further issues!

**Comment by kball-pa** [comment]
Belated thank you! The above worked.
