### ISSUE TITLE
Missing UDF in region europe-west3

### ISSUE THREAD

**Issue by ex0ns** [GoogleCloudPlatform/bigquery-utils#433]
When trying to run the following SQL code in a BigQuery project located in europe-west3

```sql
bqutil.fn_europe_west3.typeof(arr)
```

I get the following error:

```
Access Denied: Routine bqutil:fn_europe_west3.typeof: User does not have permission to invoke routine bqutil.fn_europe_west3.typeof. 
```

I guess the dataset exists otherwise the error would have been different, but is missing some permission compared to other regions:

![image](https://github.com/user-attachments/assets/a868cf99-1141-4bc3-978a-3021879e2c97)

The terraform seems to be correct https://github.com/GoogleCloudPlatform/bigquery-utils/blob/b69879efe1c02dcba8a37a5c2174795e2d76102a/release/terraform/variables.tf#L35-L37

But something might have gone wrong when making the dataset public ? Or did I overlooked something on my side regarding to permission when it comes to using those UDFs ?

Thanks !

**Comment by afleisc** [comment]
Hello, nice catch! That was a permission that was missed on our end. It has been updated and you should be able to run it now

**Comment by ex0ns** [comment]
It works. Thank you for the quick fix !
